# Generated by Django 4.2.1 on 2023-05-14 09:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="students",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="students",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.DeleteModel(
            name="AnswerSheet",
        ),
        migrations.DeleteModel(
            name="Class",
        ),
        migrations.DeleteModel(
            name="Exam",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
